version: '3.9'
networks:
  moviebook:
    driver: bridge
    name: moviebook
volumes:
  moviebook:
services:
  db:
    image: mysql:8.0.29
    container_name: moviebook-db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - moviebook
    volumes:
      - ./src/main/database/moviebook.sql:/docker-entrypoint-initdb.d/0_create.sql
  app:
    depends_on:
      - db
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
    image: erosvitor/moviebook
    container_name: moviebook-app
    restart: always
    # Estas propriedades sobrepoem as propriedades no 'application.properties'
    environment:
      TZ: America/Sao_Paulo
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://db:3308/moviebook?useTimezone=true&serverTimezone=UTC
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
    ports:
      - 8080:8080
    networks:
      - moviebook
